<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_done</name>
   <tag></tag>
   <elementGuidId>34007df8-2309-4c16-b343-a5e354576d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[text()=&quot;Done&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[text()=&quot;Done&quot;]</value>
      <webElementGuid>8beeacae-75f3-4fbe-9959-72492b4bffef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
