<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verification_setting_dialogue</name>
   <tag></tag>
   <elementGuidId>dab2955b-21a6-4049-862b-f1dec1dccccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[text()=&quot;Settings&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[text()=&quot;Settings&quot;]</value>
      <webElementGuid>c4f1a7b4-9b46-48ba-b3ea-89a0f00287f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
