<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Sanity</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>65478c77-b84d-426b-9265-088c444c9f1a</testSuiteGuid>
   <testCaseLink>
      <guid>27aead43-6701-43bf-b2e6-a82538b1c2de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3b2cd3d7-68ea-4ef6-a2c2-82ceefc66231</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6be550a-5648-4fcc-a757-1c6584be42a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5dec4d3-7327-4d69-a9d2-0e72836000a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b2cd3d7-68ea-4ef6-a2c2-82ceefc66231</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email_address</value>
         <variableId>0ed6333e-569f-4b2a-b802-9c4b74bbf1b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282e99fa-752f-4389-93ef-e95176381b0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>010dc0ad-8d26-4b68-b23e-fc8497c5252a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee7cb7c5-ee4e-4768-9f6e-371532a4220e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9de9e26e-e174-4cb0-bf8e-e02db157084d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b2cd3d7-68ea-4ef6-a2c2-82ceefc66231</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>bf4b288e-756e-442a-b5de-eba9ed64befe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1915f6a9-a2d7-4339-a404-94c12b8222fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f820b9b6-1375-4a48-a363-a99f3bf2fd63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dda142f-6c21-44f3-80d7-107d3d9d44ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Create_A_Gallery</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fabf8520-7d6a-44c6-8340-f39a404e3cdb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_CreateGallery</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dbf7d1d-c124-40ad-a9cb-1da3d0686c68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6160a01-66b1-440b-97c7-f08d013840df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0405e0d7-2fa9-443d-ad46-6bc78728369c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a8fb89-356b-432e-892e-101db4f47dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8ebe480-8e3d-42ab-be33-7dc77b112586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fabf8520-7d6a-44c6-8340-f39a404e3cdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Gallery Name</value>
         <variableId>13a969f1-ef2e-4fed-b185-95ec858e5d18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fabf8520-7d6a-44c6-8340-f39a404e3cdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Gallery Description</value>
         <variableId>d4a9fc51-09e0-4dbf-9683-9f1ac232e74b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dc2b559-37f1-4772-a055-38d43392ad54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49056716-74bf-4c3f-961c-8cd6be5d8750</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b78bf69a-9673-4495-acdc-3f59b0737f8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Edit_Gallery</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5851336d-391d-4dcc-b3c2-2fa17c8b8095</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_EditGallery</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39bc27df-608c-4bfb-ae56-af08694769e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2810941-86a3-4980-b032-5ca9e410a71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6176cc4d-7c6c-48d3-86ab-857d4e892533</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71fadd83-f603-4efe-93eb-d8a40c783276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5851336d-391d-4dcc-b3c2-2fa17c8b8095</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>afe38222-6ce3-4ba5-b591-f72623bce680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1259235a-a5e6-4407-879c-1cbb131034db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5851336d-391d-4dcc-b3c2-2fa17c8b8095</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>81f63996-ed9a-49f5-ad84-67742f03134b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acd685e-7c15-444e-9d7a-cc2432595170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6f95b59-e07e-4386-85bf-e324d63cd1b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9443009e-9a9f-4689-ba4a-2ffc6b26d965</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Upload_Piece</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1a3f367-e829-4242-811e-6ead1f04d2b3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_AddPiece_Manual</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>363250e0-87ae-41b8-8656-585118415a29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4e20585-0a30-448e-960f-51dbeb269400</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3c55c6-0d69-433d-830d-a115f9c452dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edc1bb18-2666-4f71-89a7-fa604b1416c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18d0dd3-e94b-4353-92ab-1459c1c7ccfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b03aafb-e350-458b-8db7-0ecc5bf64af0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2792488b-7172-4646-a469-0c5d2cbb6c8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2e038ef-f05f-4aab-9a2a-68dfc439ab29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2d88d57-847c-4ddf-86e3-5caab712ae2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f736596-8887-4e5b-91af-385b77b8d10f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1a3f367-e829-4242-811e-6ead1f04d2b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>55f5ac3c-cf7a-4a01-8d68-1854a8cf5a6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1a3f367-e829-4242-811e-6ead1f04d2b3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>f93d4f11-cee1-4d26-a332-7d402b76d001</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83bf5188-9ce3-4492-a101-80466b7012d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38255f7f-80fd-4899-aca6-fcf1a7912ec7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b62cf68f-ec10-4213-97dd-3cfcd1ff9daf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Edit_Asset_Setting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ce9f2cb7-1c2b-4a95-ae76-8e208033fa39</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_Asset_Settings</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50eea9b5-08c4-4284-bfa3-7e694eaeac67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2463c0a3-8501-42a7-9172-cb1f591410a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7abf1c1-a66c-478a-b635-e039f5fea821</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>894a2af1-8b1e-45b0-aa0a-da0179bec295</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6d177fb-6851-4362-a42e-a9378b2f7e54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b0c9a94-0d42-45ef-8c49-04ae116310c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fc1af48-6695-4862-a0be-ef4ec452535b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aac622d8-7e74-43f5-a1d2-1f64d62d86ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee5d2fe-69a5-4c66-b71e-236e634bfd18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4c6e3db-0c80-4457-884c-978980bafd42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0e18f0-abe1-4bfc-8f83-4551c06ccb64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412f322d-21e6-4e68-8fdd-0f3801111774</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a788e144-163d-4a42-bd34-7b937b217bcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc5de631-02a5-4ecb-9c91-b85c34dc6cb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a635253e-7ca8-4341-9873-eed6d2097209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce9f2cb7-1c2b-4a95-ae76-8e208033fa39</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>322facbc-3685-4503-a56f-e3ca36129c67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61fb9982-e752-4cb5-a21c-99bc0f445453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce9f2cb7-1c2b-4a95-ae76-8e208033fa39</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>932eeb3f-dcb0-4143-9d43-750743dc56bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc5d55ac-1147-48fb-abfb-8590667a86ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Add_via_Blockchain</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d07c1b58-2d53-47b2-a476-e7dc2aa78dd9</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Creator-Portal_DataFiles/DF_AddPiece</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a893514-7951-44d4-851f-5f68ef8a6009</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a3e989-dce1-4c1d-a127-a76416a4f81d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d4a20b-e986-440c-a5b3-fd518bae5094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a51f5765-693c-42a2-9a7f-231e9b038179</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f4b9b3-8fd0-453d-8a27-0b4090a8c5aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adf6ff57-015e-4cfd-a163-3d4102fd0c94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d07c1b58-2d53-47b2-a476-e7dc2aa78dd9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Ethereum Address</value>
         <variableId>8399607e-2620-41b0-98e3-8c09bdef5524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d07c1b58-2d53-47b2-a476-e7dc2aa78dd9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Token_ID</value>
         <variableId>638a5b84-d239-4bc1-85c3-0511a67914bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c47aef51-a805-48c1-b7ac-7f7f42780185</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a2dfd7-361f-4497-807b-fb5aff1578e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f97e1b0-2a50-45a6-8cee-1c757a150650</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab015da9-8568-444f-a1c8-31e9282c11c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8093d610-128f-4a7b-ab5d-2d6f27e9226e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44009b9c-8318-4e91-8e3d-3a441626722f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Publish_Gallery</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>710f26c0-3b7f-4ede-86dd-f20321d75dd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>017990d6-c104-4aee-8dd5-312f844cac1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20e2f693-f580-4239-b0bb-94ef13b0cf30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35ba1a8f-9907-4e84-afcf-e93aceabb57c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Remove_Piece</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97d46604-f147-41ce-86e5-f47a3099a0fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>915b49ae-6903-46e3-8dd7-896f719d5294</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e9a9af4-e8c3-4718-9bdc-46df0ac60c69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6d4d103-5f89-4be7-a039-693b6c7cd954</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5374ebae-7633-4a65-b947-173a6ec6b220</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Delete_Gallery</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbb0f5a-1f7a-4d57-b2fe-fe35617fd9bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15df427e-090a-41e9-8bda-dcc9f0b4601b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5537b67-886d-4689-a0e7-b1eb2f6bb9b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>817e95ec-6909-4506-8f27-7a4a8aa0afdf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf030f47-ae8b-467f-a7c4-c1fedaef4dc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LAGO-Creator-Portal/Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abf2a5b7-a468-464b-b7ef-3b70c20a712f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
