<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ethereum</name>
   <tag></tag>
   <elementGuidId>29d43589-aac8-430d-b005-7d1ea3d766b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;ethereum&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;ethereum&quot;]</value>
      <webElementGuid>0ca9078d-270b-4cb3-9db6-a31caa4d7dde</webElementGuid>
   </webElementProperties>
</WebElementEntity>
