<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>fc17a20f-f4c5-4d47-990e-077f5f6715af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;name&quot;]</value>
      <webElementGuid>5fc04f97-f03d-41e6-9947-ec7daac0028e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
