<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OR_Canvas</name>
   <tag></tag>
   <elementGuidId>78f0f0d1-3112-4b87-b268-ad9ed3712745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/canvas</value>
      <webElementGuid>59896388-b355-43fa-964b-629d3e733015</webElementGuid>
   </webElementProperties>
</WebElementEntity>
