<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_field</name>
   <tag></tag>
   <elementGuidId>d2ed0e6c-08b8-46af-a5ec-0b7e1b91ddcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;email-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;email-input&quot;]</value>
      <webElementGuid>315ac064-2edf-44ef-a38f-31fa895bca31</webElementGuid>
   </webElementProperties>
</WebElementEntity>
