<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_login</name>
   <tag></tag>
   <elementGuidId>6ba62886-4021-4b25-9dca-faedb55ab11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h2[text()=&quot;Login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[text()=&quot;Login&quot;]</value>
      <webElementGuid>87692c4e-156d-4c1a-8050-b5ff6a100ad1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
