<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_email</name>
   <tag></tag>
   <elementGuidId>f77a58df-20aa-4d2e-a89d-7d9199dba0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()=&quot;Email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()=&quot;Email&quot;]</value>
      <webElementGuid>7cb1a761-ce3f-40d4-9ddf-c1c18e342ac2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
