<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nameField</name>
   <tag></tag>
   <elementGuidId>47b4fe2c-e355-45ca-9958-b6619a0cc5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;name-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;name-input&quot;]</value>
      <webElementGuid>ad55a37e-4610-4b1b-8847-3755ce832539</webElementGuid>
   </webElementProperties>
</WebElementEntity>
